Repository GNU-CORNER/BookkyProject_BackEnd, pull requests merged in 2022-04, with the labels that each got.

#43 Dev/docs/swagger setting
  .gitignore
  bookky/Crawling_thumbnail 2.py
  bookky/auth.py
  bookky/bookserializers.py
  bookky/bookviews.py
  bookky/socialview.py
  bookky/urls.py
  bookky/userserializers.py
  bookky/userviews.py
  bookky_backend/settings.py
  bookky_backend/urls.py
Labels: dev/docs

#47 Dev/function/social login
  .gitignore
  bookky/migrations/0004_book_thumbnailimage_user_loginmethod.py
  bookky/migrations/0005_book_thumbnailimage_alter_user_pushtoken.py
  bookky/migrations/0006_book_thumbnailimage_alter_user_pwtoken.py
  bookky/models.py
  bookky/socialview.py
  bookky/urls.py
  bookky/userserializers.py
  bookky/userviews.py
Labels: dev/function

#49 Dev/function/tag classification
  Get_Tag.json
  Tag.json
  bookky/Tag_Classification.py
  output.json
Labels: dev/function

#55 Hotfix/model/community
  bookky/migrations/0008_anycommunity_title_book_thumbnailimage_and_more.py
  bookky/migrations/0009_book_thumbnailimage_alter_anycommunity_title_and_more.py
  bookky/migrations/0010_book_thumbnailimage_alter_anycomment_createat_and_more.py
  bookky/models.py
  bookky/serializers/communityserializers.py
Labels: Hotfix/model
